
package br.univel.VendaJaxWSclient;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaJaxWS", targetNamespace = "http://servlet.univel.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VendaJaxWS {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "operacaoVenda", targetNamespace = "http://servlet.univel.br/", className = "br.univel.VendaJaxWSclient.OperacaoVenda")
    @ResponseWrapper(localName = "operacaoVendaResponse", targetNamespace = "http://servlet.univel.br/", className = "br.univel.VendaJaxWSclient.OperacaoVendaResponse")
    public void operacaoVenda();

}
