
package br.univel.EntregaJaxWSclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EntregaJaxWSService", targetNamespace = "http://servlet.univel.br/", wsdlLocation = "http://localhost:8080/lab146560/EntregaJaxWS?wsdl")
public class EntregaJaxWSService
    extends Service
{

    private final static URL ENTREGAJAXWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENTREGAJAXWSSERVICE_EXCEPTION;
    private final static QName ENTREGAJAXWSSERVICE_QNAME = new QName("http://servlet.univel.br/", "EntregaJaxWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab146560/EntregaJaxWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTREGAJAXWSSERVICE_WSDL_LOCATION = url;
        ENTREGAJAXWSSERVICE_EXCEPTION = e;
    }

    public EntregaJaxWSService() {
        super(__getWsdlLocation(), ENTREGAJAXWSSERVICE_QNAME);
    }

    public EntregaJaxWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTREGAJAXWSSERVICE_QNAME, features);
    }

    public EntregaJaxWSService(URL wsdlLocation) {
        super(wsdlLocation, ENTREGAJAXWSSERVICE_QNAME);
    }

    public EntregaJaxWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTREGAJAXWSSERVICE_QNAME, features);
    }

    public EntregaJaxWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntregaJaxWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EntregaJaxWS
     */
    @WebEndpoint(name = "EntregaJaxWSPort")
    public EntregaJaxWS getEntregaJaxWSPort() {
        return super.getPort(new QName("http://servlet.univel.br/", "EntregaJaxWSPort"), EntregaJaxWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntregaJaxWS
     */
    @WebEndpoint(name = "EntregaJaxWSPort")
    public EntregaJaxWS getEntregaJaxWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servlet.univel.br/", "EntregaJaxWSPort"), EntregaJaxWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTREGAJAXWSSERVICE_EXCEPTION!= null) {
            throw ENTREGAJAXWSSERVICE_EXCEPTION;
        }
        return ENTREGAJAXWSSERVICE_WSDL_LOCATION;
    }

}
