
package br.univel.EntregaJaxWSclient;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntregaJaxWS", targetNamespace = "http://servlet.univel.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntregaJaxWS {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "operacaoEntrega", targetNamespace = "http://servlet.univel.br/", className = "br.univel.EntregaJaxWSclient.OperacaoEntrega")
    @ResponseWrapper(localName = "operacaoEntregaResponse", targetNamespace = "http://servlet.univel.br/", className = "br.univel.EntregaJaxWSclient.OperacaoEntregaResponse")
    public void operacaoEntrega();

}
