
package br.univel.ProdutoJaxWSclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProdutoJaxWS", targetNamespace = "http://webservice.univel.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProdutoJaxWS {


    /**
     * 
     * @return
     *     returns java.util.List<br.univel.ProdutoJaxWSclient.Produto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readAll", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.ReadAll")
    @ResponseWrapper(localName = "readAllResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.ReadAllResponse")
    public List<Produto> readAll();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProduto", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.DeleteProduto")
    @ResponseWrapper(localName = "deleteProdutoResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.DeleteProdutoResponse")
    public void deleteProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        Produto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.univel.ProdutoJaxWSclient.Produto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readProduto", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.ReadProduto")
    @ResponseWrapper(localName = "readProdutoResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.ReadProdutoResponse")
    public Produto readProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createProduto", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.CreateProduto")
    @ResponseWrapper(localName = "createProdutoResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.CreateProdutoResponse")
    public void createProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        Produto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateProduto", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.UpdateProduto")
    @ResponseWrapper(localName = "updateProdutoResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.ProdutoJaxWSclient.UpdateProdutoResponse")
    public void updateProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        Produto arg0);

}
