
package br.univel.ProdutoJaxWSclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProdutoJaxWSService", targetNamespace = "http://webservice.univel.br/", wsdlLocation = "http://localhost:8080/lab146560/ProdutoJaxWS?wsdl")
public class ProdutoJaxWSService
    extends Service
{

    private final static URL PRODUTOJAXWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUTOJAXWSSERVICE_EXCEPTION;
    private final static QName PRODUTOJAXWSSERVICE_QNAME = new QName("http://webservice.univel.br/", "ProdutoJaxWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab146560/ProdutoJaxWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUTOJAXWSSERVICE_WSDL_LOCATION = url;
        PRODUTOJAXWSSERVICE_EXCEPTION = e;
    }

    public ProdutoJaxWSService() {
        super(__getWsdlLocation(), PRODUTOJAXWSSERVICE_QNAME);
    }

    public ProdutoJaxWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUTOJAXWSSERVICE_QNAME, features);
    }

    public ProdutoJaxWSService(URL wsdlLocation) {
        super(wsdlLocation, PRODUTOJAXWSSERVICE_QNAME);
    }

    public ProdutoJaxWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUTOJAXWSSERVICE_QNAME, features);
    }

    public ProdutoJaxWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdutoJaxWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProdutoJaxWS
     */
    @WebEndpoint(name = "ProdutoJaxWSPort")
    public ProdutoJaxWS getProdutoJaxWSPort() {
        return super.getPort(new QName("http://webservice.univel.br/", "ProdutoJaxWSPort"), ProdutoJaxWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProdutoJaxWS
     */
    @WebEndpoint(name = "ProdutoJaxWSPort")
    public ProdutoJaxWS getProdutoJaxWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.univel.br/", "ProdutoJaxWSPort"), ProdutoJaxWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUTOJAXWSSERVICE_EXCEPTION!= null) {
            throw PRODUTOJAXWSSERVICE_EXCEPTION;
        }
        return PRODUTOJAXWSSERVICE_WSDL_LOCATION;
    }

}
